Repository theakhiljha/Ultimate-Logic, pull requests merged in 2020-10, with the labels that each got.

#38 code to convert to octal form
  octal/octal.c
Labels: Hacktoberfest

#37 Factorial Program
  Factorial/Factorial.java
Labels: Hacktoberfest

#40 Create reverse.c
  reverse/reverse.c
Labels: Hacktoberfest

#41 UPC code
  validity_of_UPC/validity_of_UPC.c
Labels: Hacktoberfest

#31 Create Matric Transpose.cpp
  Matrix/Matrix Transpose.cpp
Labels: Hacktoberfest

#63 Create BubbleSort.cpp
  Array/Rotate-Array/RotateArr.cpp
  Sorting/Bubble Sort/BubbleSort.cpp
  Sorting/Insertion Sort/InsertionSort.cpp
  Sorting/Merge Sort/MergeSort.cpp
  Sorting/Quick Sort/QuickSort.cpp
  Sorting/Selection Sort/SelectionSort.cpp
Labels: Hacktoberfest

#73 Created Greedy Algo/ Fractional_Knapsack.cpp
  Greedy Algo/Fractional_Knapsack.cpp
Labels: Hacktoberfest

#71 Add files via upload (check_right_angled_triangle.py)
  Triangle/check_right_angled_triangle.py
Labels: Hacktoberfest

#45 Sorting an array of 0's,1's and 2's
  Array/OddNumberOfTimes.java
  Arrays/MaximumOfAllSubarrays.java
  BackTracking/countPalindromeSubstringsOfString.java
  Backtracking/decoding_messages.java
  Dynamic-Programming/knapsack_0_1.java
  Dynamic-Programming/longest_common_subsequence.java
  HashMap/KeyPair.java
  Sorting/three_way_partitioning.java
Labels: hacktoberfest-accepted

#43 Factorial in c++
  Factorial/Factorial.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#77 Create calculator.py
  calculator/calculator.py
Labels: hacktoberfest-accepted

#76 Create magic_sq.c
  To create a magic square*/magic_sq.c
Labels: hacktoberfest-accepted

#60 Create calc_scrabble_val.c
  ScrabbleCalc/calc_scrabble_val.c
Labels: hacktoberfest-accepted

#59 Created a user defined linear search
  Searching/Linear Search/Linear-Search.c
Labels: hacktoberfest-accepted

#58 Added caesar.c
  Encryption/Caesar Cipher/caesar.c
Labels: hacktoberfest-accepted

#57 Create LargestAreaHistogram.cpp
  Climb Stairs with Min Move/minMove.cpp
  Stacks/BalancedBrackets.cpp
  Stacks/LargestAreaHistogram.cpp
  Stairs with Variable Jump/stairsvariablejump.cpp
Labels: hacktoberfest-accepted

#50 Create collatz.cpp
  collatz/collatz.cpp
Labels: hacktoberfest-accepted

#49 added binary.c
  Binary/binary.c
Labels: hacktoberfest-accepted

#48 radixsort
  Graph/Djikstra.js
  Sorting/RadixSort.js
Labels: hacktoberfest-accepted

#42 Beaufort scale
  Beaufort Scale/beaufort_scale.c
Labels: hacktoberfest-accepted

#33 2 leetcode questions added with their C++ solutions and question links
  Matrix/Queue-reconstruction-by-height/Link.txt
  Matrix/Queue-reconstruction-by-height/Queue Reconstruction by Height.cpp
  Matrix/Score after flipping matrix/Question link.txt
  Matrix/Score after flipping matrix/Score After Flipping Matrix.cpp
Labels: hacktoberfest-accepted

#30 added more files
  Matrix/Matrix Multiplication/dynamic_multiplication.c
  Matrix/Matrix Multiplication/recursivemultiplication.c
  Matrix/Matrix Multiplication/strassens_matrix_multiplication.c
  Matrix/Problems/greedyknapsacks.c
  Matrix/Problems/towerofhanoi.c
  Matrix/Sum Of Two Matrix/add_matrices_recursion.c
  Matrix/Transpose/transpose_dynamic.c
  Searching/Longest Common Subsequence/094_longestcommonsubsequence.c
Labels: hacktoberfest-accepted

#29 Create BinarySearch.java
  Searching/Binary Search/BinarySearch.java
Labels: hacktoberfest-accepted

#22 Transpose of matrix added
  Matrix/Transpose of a matrix/transpose.cpp
Labels: hacktoberfest-accepted

#13 Create binary_search.cpp
  Searching/Binary Search/binary_search.cpp
Labels: hacktoberfest-accepted

#18 Added Spiral Matrix Traversal Problem
  Matrix/Spiral Matrix/Spiral Traversal of a Matrix/Spiral Matrix Traversal.cpp
Labels: hacktoberfest-accepted

#20 Create search_sort.c
  Matrix/matrix_minimize/matrix_minimize_cost.c
  Sorting/Search Sorting/search_sort.c
Labels: hacktoberfest-accepted

#21 Sorting Algorithms in Python
  Sorting/sorting in Python/bubblesort.py
  Sorting/sorting in Python/insertionsort.py
  Sorting/sorting in Python/mergesort.py
  Sorting/sorting in Python/selectionsort.py
Labels: hacktoberfest-accepted

#7 added sorting folder and insertion sort algorithm
  Matrix/matrix multiplication 1.cpp
  Sorting/insertion_sort.cpp
Labels: hacktoberfest-accepted
